apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
stringData:
  db_password: "LabPassword123!"
  db_host: "k8s-lab-mysql.c7osis4g47d7.us-east-1.rds.amazonaws.com"
  db_name: "wordpressdb"
  db_user: "admin"