apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  selector:
    # Pilih pod yang punya label app: wordpress
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80           # port di dalam cluster
      targetPort: 80     # port di container
      nodePort: 30080    # port yang diakses ALB